# kubectl create secret docker-registry myregistrykey --docker-server=<your-registry-server> --docker-username=<your-username> --docker-password=<your-password> --docker-email=<your-email>
apiVersion: v1
kind: Pod
metadata:
  name: private-repo
spec:
  containers:
  - name: webserver
    image: <your-private-image>
    imagePullSecrets:
    - name: myregistrykey